<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("");


?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search", 
	"search", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "SCALED_PRICE_1",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "L",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "5",
		"IBLOCK_TYPE" => "catalog",
		"LINE_ELEMENT_COUNT" => "4",
		"NO_WORD_LOGIC" => "N",
		"OFFERS_LIMIT" => "0",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "500",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array(
			0 => "IIKO_ID",
			1 => "imageid",
			2 => "weight",
			3 => "WEIGHT_OFFER",
			4 => "YOUTUBE_LINK",
      5 => "RUTUBE_LINK",
			6 => "VARIANTS",
			7 => "isincludedinmenu",
			8 => "OTHER_PRODUCTS",
			9 => "measureunit",
			10 => "fatamount",
			11 => "fiberamount",
			12 => "carbohydrateamount",
			13 => "modifiers",
			14 => "NAME_H1",
			15 => "donotprintincheque",
			16 => "CHARACTER_PRODUCT_SCORE",
			17 => "fatfullamount",
			18 => "fiberfullamount",
			19 => "carbohydratefullamount",
			20 => "energyfullamount",
			21 => "POPULAR",
			22 => "PRODUCT_SIZE",
			23 => "RECEPT",
			24 => "RECOMMENDED",
			25 => "FRESH",
			26 => "DISCOUNT_PERCENT",
			27 => "CHARACTER_STRUCTURE",
			28 => "CHARACTER_EXPIRATION_DATE",
			29 => "CHARACTER_COUNTRY",
			30 => "type",
			31 => "CHARACTER_PACKAGE",
			32 => "CHARACTER_STORAGE_CONDITIONS",
			33 => "SORT_PRICE",
			34 => "COST_DISCOUNT",
			35 => "STEP_TO_ADD",
			36 => "",
		),
		"RESTART" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_SEARCH_RESULT_ORDER" => "Y",
		"USE_TITLE_RANK" => "Y",
		"COMPONENT_TEMPLATE" => "search"
	),
	false
);?><br><?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");
?>